# Generated by Django 3.2.17 on 2023-02-10 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('idProgram', models.AutoField(primary_key=True, serialize=False)),
                ('nameProgram', models.CharField(db_column='Name', max_length=248)),
                ('validityDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Program Validity Date')),
            ],
            options={
                'db_table': 'tblProgram',
            },
        ),
    ]
