# Generated by Django 3.2.17 on 2023-02-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_last_login_on_interactive_user'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='user',
            field=models.ManyToManyField(to='core.InteractiveUser'),
        ),
    ]
