# Generated by Django 3.2.23 on 2023-11-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20230315_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, db_column='programCode', max_length=10, null=True),
        ),
    ]
